Try out EnricoMi/publish-unit-test-result-action again

diff --git a/.github/workflows/new-test.yml b/.github/workflows/new-test.yml
--- a/.github/workflows/new-test.yml
+++ b/.github/workflows/new-test.yml
@@ -49,9 +49,9 @@ jobs:
           large-packages: true
           docker-images: true
           swap-storage: true
-      - name: "remove nextest ci directory"
+      - name: "Remove nextest CI report"
         shell: bash
-        run: rm -rf target/nextest/ci*
+        run: rm -rf target/nextest/ci/junit.xml
       - name: "[${{ steps.rust-version.outputs.version }}] cargo build --workspace --verbose"
         run: cargo build --workspace --verbose
       - name: "[${{ steps.rust-version.outputs.version }} WIN] cargo nextest run --profile ci --verbose"
@@ -66,14 +66,20 @@ jobs:
         env:
           RUST_BACKTRACE: 1
           # TODO do we need to create multiple junit files for the different test runs
+      # - name: Report Test Results
+      #   if: success() || failure() 
+      #   uses: mikepenz/action-junit-report@v4
+      #   with:
+      #     report_paths: "target/nextest/ci/*.xml"
+      #     check_name: "[${{ matrix.platform }}:${{ matrix.rust_version }}] test report"
+      #     include_passed: true
       - name: Report Test Results
         if: success() || failure() 
-        uses: mikepenz/action-junit-report@v4
+        uses: EnricoMi/publish-unit-test-result-action@v2
         with:
-          report_paths: "target/nextest/ci/*.xml"
+          files: "target/nextest/ci/junit.xml"
           check_name: "[${{ matrix.platform }}:${{ matrix.rust_version }}] test report"
-          include_passed: true
-
+          comment_mode: "off"
       # - name: "Save Test Results"
       #   if: success() || failure() # always upload test results unless canceled
       #   uses: actions/upload-artifact@v4
