Try need with matrix job name

diff --git a/.github/workflows/new-test.yml b/.github/workflows/new-test.yml
--- a/.github/workflows/new-test.yml
+++ b/.github/workflows/new-test.yml
@@ -66,20 +66,24 @@ jobs:
         env:
           RUST_BACKTRACE: 1
           # TODO do we need to create multiple junit files for the different test runs
-      # - name: Report Test Results
-      #   if: success() || failure() 
-      #   uses: mikepenz/action-junit-report@v4
-      #   with:
-      #     report_paths: "target/nextest/ci/*.xml"
-      #     check_name: "[${{ matrix.platform }}:${{ matrix.rust_version }}] test report"
-      #     include_passed: true
       - name: Report Test Results
         if: success() || failure() 
-        uses: EnricoMi/publish-unit-test-result-action@v2
+        uses: mikepenz/action-junit-report@v4
         with:
-          files: "target/nextest/ci/junit.xml"
+          report_paths: "target/nextest/ci/*.xml"
           check_name: "[${{ matrix.platform }}:${{ matrix.rust_version }}] test report"
-          comment_mode: "off"
+          include_passed: true
+      - name: Report required results
+        if: success() && ${{ matrix.platform == 'ubuntu-latest' }} && ${{ matrix.rust_version == '1.71.1' }}
+        run: echo "required_1_passed=true" >> $GITHUB_OUTPUT;
+
+      # - name: Report Test Results
+      #   if: success() || failure() 
+      #   uses: EnricoMi/publish-unit-test-result-action@v2
+      #   with:
+      #     files: "target/nextest/ci/junit.xml"
+      #     check_name: "[${{ matrix.platform }}:${{ matrix.rust_version }}] test report"
+      #     comment_mode: "off"
       # - name: "Save Test Results"
       #   if: success() || failure() # always upload test results unless canceled
       #   uses: actions/upload-artifact@v4
@@ -107,3 +111,14 @@ jobs:
   #         with:
   #           report_paths: "artifacts/**/*.xml"
   #           check_name: "Report Test Results"
+  required-tests:
+    runs-on: ubuntu-latest
+    needs: [test]
+    if: success() || failure()
+    steps:
+      - name: Required success
+        if: ${{ needs.test.outputs.required_1_passed == 'true' }}
+        run: echo "Required tests passed"
+      - name: Required failure
+        if: ${{ needs.test.outputs.required_1_passed != 'true' }}
+        run: echo "Required tests failed" && exit 1
